apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-application-name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: your-application
  template:
    metadata:
      labels:
        app: your-application
    spec:
      containers:
      - name: your-application-container
        image: prachi24oracle/my-flask-app_jenkins:latest
        ports:
        - containerPort: 80
